kind: wasmer.io/App.v0
name: event-hall-mockup
app_id: da_2l9IzteUYVo6
owner: aisyahhei8482
package: .
locality:
  regions:
  - fr-roub1
env:
  PHPIX_PHP_THREADS: '4'
volumes:
- name: laravel-uploads
  mount: /app/storage/app/public
annotations:
  anybuild.run/config:
    commands:
      install: 'php artisan storage:link'
    composer_build_script: post-update-cmd
    composer_enable: false
    name: out
    node_build_command: npm run build
    node_install_inputs:
    - package.json
    node_package_manager: npm
    npm_version: '11'
    php_framework: laravel
    php_public_dir: public
    phpix: true
  anybuild.run/provider: laravel
  anybuild.run/version: 0.29.0
  wasmer.io/version: 7.4.2
enableDatabase: true
